# Generated by Django 5.2.3 on 2025-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=50)),
                ('store_id', models.CharField(max_length=20)),
                ('product_id', models.CharField(max_length=20)),
                ('stock', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('shelf_life_days', models.IntegerField()),
                ('avg_daily_sales', models.FloatField()),
                ('MRP', models.FloatField()),
                ('days_to_expiry', models.IntegerField()),
                ('remaining_ratio', models.FloatField()),
                ('expected_sales', models.FloatField()),
                ('predicted_demand', models.FloatField()),
                ('discount', models.FloatField()),
                ('final_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('from_store', models.CharField(max_length=20)),
                ('to_store', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('distance_km', models.FloatField()),
                ('remaining_ratio', models.FloatField()),
                ('days_to_expiry', models.IntegerField()),
            ],
        ),
    ]
