# Generated by Django 5.2.3 on 2025-07-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
